version: "3.9"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    user: root
    # command: start --log trace file:/data/database.db
    command:
      - start
      - --log=trace
      - --user=root
      - --pass=root
      - file:/data/database.db
    container_name: surrealdb
    ports:
      - 8000:8000
    volumes:
      - data_volume:/data

volumes:
  data_volume:
