version: "3.9"

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
    environment:
      - SCYLLA_CLUSTER_NAME=mycluster
      - SCYLLA_ENDPOINT_SNITCH=SimpleSnitch
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_BROADCAST_ADDRESS=scylla
      - SCYLLA_BROADCAST_RPC_ADDRESS=scylla
      - SCYLLA_SEEDS=scylla
    command: --authenticator PasswordAuthenticator --authorizer CassandraAuthorizer

volumes:
  scylla-data:
